# Generated by Django 4.2.5 on 2023-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
